app/__init__.py
# -*- coding: utf-8 -*-
import logging

from celery import Celery, Task
from flask import Flask


def create_app():
    app = Flask(__name__)

    app.config["CELERY"] = {
        "broker_url": "redis://redis:6379/0",
        "result_backend": "redis://redis:6379/0",
        "task_ignore_result": False
    }

    celery_init_app(app)

    app.logger.setLevel(logging.ERROR)
    logging.basicConfig(filename="app/logs/main.log",
                        format="%(asctime)s - %(name)s - %(levelname)s - %(message)s")  # noqa: E501

    from . import routes
    app.register_blueprint(routes.bp, url_prefix="/")

    return app


def celery_init_app(app: Flask):
    class FlaskTask(Task):
        def __call__(self, *args: object, **kwargs: object):
            with app.app_context():
                return self.run(*args, **kwargs)

    celery_app = Celery(app.name, task_cls=FlaskTask)
    celery_app.config_from_object(app.config["CELERY"])
    celery_app.set_default()
    app.extensions["celery"] = celery_app
    return celery_app

app/routes.py
# -*- coding: utf-8 -*-
import io
import os

from flask import (
    Blueprint,
    send_file,
    current_app,
    redirect,
    url_for,
    make_response,
    request,
    render_template
)
import yt_dlp

from .tasks import ytsampler
from .ydl_options import ydl_opts


bp = Blueprint("core", __name__)


@bp.route("/")
def interface_index():
    """
    Serve simple interface to interact with the API endpoints.
    """
    return render_template("index.html")


@bp.route("/extract", methods=["GET", "POST"])
def extract():
    """
    Start a celery task to extract a clip based on the start and end parameters. # noqa: E501
    """

    if request.method == "GET":
        current_app.logger.debug("Extract GET")
        url = request.args.get("url", None)
        start = request.args.get("start", None)
        end = request.args.get("end", None)
        current_app.logger.debug(f"{url} {start} {end}")

        if None in (url, start, end):
            return make_response(
                {"error": "Missing parameter. Provide url, start and end."}
            )
        current_app.logger.debug("extractor")
        yt_extractor = yt_dlp.extractor.get_info_extractor("Youtube")
        is_valid_link = yt_extractor.suitable(url)
        current_app.logger.debug("extracted")

        if not is_valid_link:
            current_app.logger.debug("Invalid url: {}".format(url))
            return make_response({"error": "Invalid url."}, 400)

        current_app.logger.debug("sampler")
        try:
            audio = ytsampler.apply_async(
                args=[url, ydl_opts, start, end])
        except Exception as e:
            current_app.logger.debug("Something went wrong tasking celery.")
            current_app.logger.debug(repr(e))

        current_app.logger.debug("postsampler")

        check_url = url_for("core.taskstatus", task_id=audio.id)

        return redirect(check_url)

    if request.method == "POST":
        current_app.logger.debug("Extract POST")
        url = request.form.get("url", None)
        start = request.form.get("start", None)
        end = request.form.get("end", None)
        current_app.logger.debug(f"{url} {start} {end}")

        if None in (url, start, end):
            return render_template(
                "failure.html", message="Missing parameter. Provide url, start and end."  # noqa: E501
            )

        try:
            yt_extractor = yt_dlp.extractor.get_info_extractor("Youtube")
            is_valid_link = yt_extractor.suitable(url)
        except Exception as e:
            current_app.logger.debug("Error calling ty_dlp.")
            current_app.logger.debug(repr(e))

        if not is_valid_link:
            current_app.logger.debug("Invalid url: {}".format(url))
            return render_template("failure.html", message="Invalid url.")

        current_app.logger.debug("pre task")

        try:
            audio = ytsampler.apply_async(
                args=[url, ydl_opts, start, end])
            current_app.logger.debug(audio)
        except Exception as e:
            current_app.logger.debug("Something went wrong tasking celery.")
            current_app.logger.debug(repr(e))

        return render_template("check_status.html", task_id=audio.id, html=True)  # noqa: E501


@bp.route("/segment")
def segment():
    """
    Start the celery task to segment an audio file into ... segments.
    """

    url = request.args.get("url")
    segment_len = request.args.get("segment_len")

    audio = ytsampler.apply_async(
        args=[url, ydl_opts, None, None],
        kwargs={"segment_len": segment_len, "segment": True},
    )

    return redirect(url_for("core.taskstatus", task_id=audio.id))


@bp.route("/status", methods=["GET"])
def taskstatus():
    """
    Check celery task status.
    """
    task_id = request.args.get("task_id")
    html = request.args.get("html", False)

    response = {"state": None, "message": None, "download_urls": None}

    if not task_id:
        response["message"] = "Missing request argument `task_id`."
        return make_response(response, 400)

    task = ytsampler.AsyncResult(task_id)

    if html:
        if task.state == "PENDING":
            return render_template("check_status.html", task_id=task_id)
        elif task.state == "FAILURE":
            current_app.logger.error(task.result)
            return render_template("failure.html")
        elif task.state == "SUCCESS":
            dl_url = url_for("core.download", path=task.result)
            return render_template("result.html", dl_url=dl_url)
    else:
        response["state"] = task.state

        if task.state == "PENDING":
            response["message"] = "Task still in progress."
            return make_response(response, 200)

        elif task.state == "SUCCESS":
            if isinstance(task.result, list):
                result = [url_for("core.download", path=n)
                          for n in task.result]
            else:
                result = url_for("core.download", path=task.result)

            response["download_urls"] = result
            return make_response(response, 200)

        elif task.state == "FAILURE":
            current_app.logger.error(task.result)
            response["message"] = "Something went wrong."
            return make_response(response)


@bp.route("/download/<path:path>")
def download(path):
    """
    Download a file.
    """
    spl = path.rsplit("/", 1)
    fname = spl[-1]
    folder = spl[0]

    return_data = io.BytesIO()
    with open(path, "rb") as fo:
        return_data.write(fo.read())

    return_data.seek(0)

    os.remove(path)

    try:
        os.rmdir(folder)
    except Exception as e:
        current_app.logger.error(f"Error removing temp folder: {repr(e)}")

    return send_file(
        return_data,
        mimetype="audio/mpeg",
        download_name=fname,
        as_attachment=True,
    )

app/templates/check_status.html
<div id="checkurl" hx-get="{{ url_for('core.taskstatus', task_id=task_id, html=True) }}" hx-trigger="every 3s" hx-swap="outerHTML">
  <div class="status">
    <img src="{{ url_for('static', filename='puff.svg') }}" alt="Processing ...">
  </div>
</div>

app/templates/failure.html
<div class="error">
  <p>Something went wrong.</p>
  {% if message %}
    <p>{{ message }}</p>
  {% endif %}
  <p><a class="reset" href="{{ url_for('core.interface_index')}}">Reset</a></p>
</div>

app/templates/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>YT sampler</title>
    <script src="https://unpkg.com/htmx.org@1.9.8"></script>
    <style media="screen">
      @import url('https://fonts.googleapis.com/css2?family=Do+Hyeon&display=swap');
      body {
        background: aliceblue;
        font-family: 'Do Hyeon', sans-serif;
      }
      #app {
        max-width: 500px;
        margin-left: auto;
        margin-right: auto;
      }
      input {
        display: block;
        margin: 1rem 0 1rem 0;
        line-height: 1.5rem;
        padding: 3px;
        border: none;
      }
      input[name="url"] {
        min-width: 400px;
      }
      .buttons {
        display: flex;
        justify-content: space-around;
        margin-top: 2rem;
      }
      .buttons button {
        line-height: 1.5rem;
        background: white;
        border: 1px solid black;
        cursor: pointer;
      }
      .buttons button:disabled {
        cursor: not-allowed;
      }
      .status {
        width: 100%;
        height: auto;
        text-align: center;
        margin-top: 3rem;
      }
      .status > img {
        margin: auto;
        height: 200px;
      }
      .debug {
        margin-top: 100px;
        display: none;
      }
      span.error {
        font-size: 0.75rem;
        color: red;
      }
    </style>
  </head>
  <body>
    <div id="app">
      <h1>Hello sample person.</h1>

      <div v-if="this.form.url" id="player"></div>

      <div id="form">
        <form
          class="mainform"
          hx-post="{{ url_for('core.extract') }}"
          hx-params="url,start,end"
        >
          <input
            type="text"
            name="url"
            v-model="form.url"
            placeholder="youtube URL"
          >
          <span class="error" v-if="errors.validUrl != 1">Must be a valid youtube url.</span>

          <input
            type="number"
            step="0.1"
            name="start-og"
            v-model="form.start"
            placeholder="start time (in seconds)"
          >
          <input
            type="hidden"
            name="start"
            :value=startInMs
          >

          <input
            type="number"
            step="0.1"
            name="end-og"
            v-model="form.end"
            placeholder="end time (in seconds)"
          >
          <span class="error" v-if="errors.validEnd != 1">End value must be larger than start value.</span>
          <input
            type="hidden"
            name="end"
            :value=endInMs
          >

          <div class="buttons">
            <button
              type="button"
              name="button"
              :disabled="readyToPostToAPI === 0"
              @click="createYtPlayer()"
            >(Re)load preview</button>

            <button
              type="submit"
              name="button"
              :disabled="readyToPostToAPI === 0"
            >Get audio file</button>
          </div>
        </form>
      </div>

      <div id="results">
      </div>

      <div class="debug">
        <code>
          Debug <br>
          ----- <br>
          Url: [[ form.url ]] <br>
          Start: [[ form.start ]] <br>
          End: [[ form.end ]] <br>
          Id: [[ videoId ]] <br>
          ready: [[ readyToPostToAPI ]] <br>
        </code>
      </div>
    </div>

    <script type="module">
      import { createApp } from 'https://unpkg.com/vue@3/dist/vue.esm-browser.js'

      const vueApp = createApp({
        data() {
          return {
            form: {
              url: null, //https://www.youtube.com/watch?v=1GVvathFQgM
              start: null,
              end: null,
            },
            ytplayer: null,
            errors: {
              validUrl: 1,
              validEnd: 1,
            }
          }
        },
        delimiters: ['[[', ']]'],
        computed: {
          videoId () {
            if (this.form.url) {
              try {
                const urlParams = new URL(this.form.url)
                return urlParams.searchParams.get('v')
              } catch (e) {
                return ''
              }
            }
            return ''
          },
          readyToPostToAPI() {
            if (this.form.url !== null && this.form.start !== null && this.form.end !== null) {

              if (!this.form.url.startsWith("https://www.youtube.com")) {
                this.errors.validUrl = 0
                return 0
              } else {
                this.errors.validUrl = 1
              }

              if (this.form.start >= this.form.end) {
                this.errors.validEnd = 0
                return 0
              } else {
                this.errors.validEnd = 1
              }
              return 1
            } else {
              return 0
            }
          },
          startInMs() {
            return this.form.start*1000
          },
          endInMs() {
            return this.form.end*1000
          }
        },
        mounted() {
          var tag = document.createElement('script');

          tag.src = "https://www.youtube.com/iframe_api";
          var firstScriptTag = document.getElementsByTagName('script')[0];
          firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);
        },
        methods: {
          onPlayerReady(event) {
           event.target.seekTo(this.form.start);
           event.target.playVideo();
          },
          onPlayerStateChange(event) {
            if (event.data == YT.PlayerState.PLAYING) {
              var duration = this.form.end - this.form.start;
              setTimeout(this.restartVideoSection, duration * 1000);
            }
          },
          restartVideoSection() {
            this.ytplayer.seekTo(this.form.start);
          },
          restartWithNewUrl() {
            console.log("new url")
            this.ytplayer.loadVideoById(this.videoId)
            console.log(this.videoId)
          },
          createYtPlayer() {
            if (this.ytplayer !== null) {
              this.restartWithNewUrl()
            } else {
              this.ytplayer = new YT.Player('player', {
                height: '390',
                width: '640',
                videoId: this.videoId,
                playerVars: {
                  'playsinline': 1
                },
                events: {
                  'onReady': this.onPlayerReady,
                  'onStateChange': this.onPlayerStateChange
                }
              });
            }
          }
        }
      })

      vueApp.mount('#app')
    </script>


  </body>
</html>

app/templates/result.html
<div class="result">
  <p><a class="download" href="{{ dl_url }}">Download</a></p>
  <p><a class="reset" href="{{ url_for('core.interface_index')}}">Reset</a></p>
</div>